### PR TITLE
Fixed bug with strange LockTargetState

### PR DESCRIPTION
**Pull request by gijoecool**

### CODE REVIEW

**Comment by SphtKr** [comment]
That's really weird...so, when you told Siri to unlock the door, `false` was getting passed into this function, but when you did it with the Home app, a numeric `0` was being passed in?? That's nuts.

Can you check your globally installed npm versions of `homebridge` and/or `hap-nodejs`? I wonder if this is something that has been fixed upstream. Even so, I can't fathom what would cause the Siri action to differ from the Home app action.

**Comment by klaasjoerg** [comment]
Don't know if it helps, but I also noticed this kind of behaviour already a couple of times, that a siri voice command sometimes acts differently than manually pushing the same designated button in Home-App (or eve app).

**Comment by gijoecool** [comment]
@SphtKr, I'll check after work tonight to see if there is difference still. I updated Node.js yesterday and ended up gutting a bunch of stuff. FWIW, someone else had the same problem on [homebridge-smartthings #126](https://github.com/pdlove/homebridge-smartthings/issues/126).

**Comment by SphtKr** [comment]
I've noticed Siri failing a whole lot more often, or working but telling me the devices "weren't interested..." maybe they're related. ?!?

**Comment by gijoecool** [comment]
@SphtKr, it looks like the issue is still the same. FYI, these logs are using this PR.

Here are my software versions:

```
pi@raspberrypi3:~ $ sudo npm ls -g --depth=0
/usr/lib
├── airsonos@0.2.6
├── hap-nodejs@0.4.21
├── homebridge@0.4.16
├── homebridge-zway@0.5.0-rc0
├── node-gyp@3.4.0
└── npm@4.0.5

npm ERR! extraneous: bignum@0.12.5 /usr/lib/node_modules/homebridge/node_modules/bignum
```

Here is the Home app:

```
Tue, 03 Jan 2017 23:56:35 GMT EventedHTTPServer [::ffff:192.168.1.248] HTTP request: /characteristics
Tue, 03 Jan 2017 23:56:35 GMT HAPServer [CC:22:3D:E3:CE:31] HAP Request: PUT /characteristics
Tue, 03 Jan 2017 23:56:35 GMT Accessory [Homebridge-pi3] Processing characteristic set: [{"aid":2,"iid":10,"value":0}]
Tue, 03 Jan 2017 23:56:35 GMT Accessory [Homebridge-pi3] Setting Characteristic "Lock Target State" to value 0
Tue, 03 Jan 2017 23:56:35 GMT EventedHTTPServer [fe80::18ed:e196:d6a8:362c] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":0}]}
Tue, 03 Jan 2017 23:56:35 GMT EventedHTTPServer [::ffff:192.168.1.24] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":0}]}
Tue, 03 Jan 2017 23:56:35 GMT EventedHTTPServer [::ffff:192.168.1.243] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":0}]}
Tue, 03 Jan 2017 23:56:35 GMT EventedHTTPServer [::ffff:192.168.1.248] Muting event '2.10' notification for this connection since it originated here.
Tue, 03 Jan 2017 23:56:35 GMT ZWayServer Device Back Door, characteristic Lock Target State changed from 1 to 0
Tue, 03 Jan 2017 23:56:35 GMT EventedHTTPServer [::ffff:192.168.1.248] HTTP Response is finished
Tue, 03 Jan 2017 23:56:42 GMT ZWayServer Got 1 updates.
Tue, 03 Jan 2017 23:56:42 GMT EventedHTTPServer [fe80::18ed:e196:d6a8:362c] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":0}]}
Tue, 03 Jan 2017 23:56:42 GMT EventedHTTPServer [::ffff:192.168.1.24] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":0}]}
Tue, 03 Jan 2017 23:56:42 GMT EventedHTTPServer [::ffff:192.168.1.243] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":0}]}
Tue, 03 Jan 2017 23:56:42 GMT EventedHTTPServer [::ffff:192.168.1.248] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":0}]}
Tue, 03 Jan 2017 23:56:42 GMT ZWayServer Device Back Door, characteristic Lock Current State changed from 1 to 0
Tue, 03 Jan 2017 23:56:42 GMT ZWayServer Updated characteristic Lock Current State on Back Door
Tue, 03 Jan 2017 23:56:42 GMT ZWayServer Returning LockTargetState of "0" because vdev.metrics.level returned "open"
Tue, 03 Jan 2017 23:56:44 GMT ZWayServer Got 1 updates.
Tue, 03 Jan 2017 23:56:44 GMT ZWayServer Returning LockTargetState of "0" because vdev.metrics.level returned "open"
```

Here is Siri:

```
Tue, 03 Jan 2017 23:57:37 GMT EventedHTTPServer [::ffff:192.168.1.248] HTTP request: /characteristics
Tue, 03 Jan 2017 23:57:37 GMT HAPServer [CC:22:3D:E3:CE:31] HAP Request: PUT /characteristics
Tue, 03 Jan 2017 23:57:37 GMT Accessory [Homebridge-pi3] Processing characteristic set: [{"aid":2,"iid":10,"value":false}]
Tue, 03 Jan 2017 23:57:37 GMT Accessory [Homebridge-pi3] Setting Characteristic "Lock Target State" to value false
Tue, 03 Jan 2017 23:57:37 GMT EventedHTTPServer [fe80::18ed:e196:d6a8:362c] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":false}]}
Tue, 03 Jan 2017 23:57:37 GMT EventedHTTPServer [::ffff:192.168.1.24] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":false}]}
Tue, 03 Jan 2017 23:57:37 GMT EventedHTTPServer [::ffff:192.168.1.243] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":false}]}
Tue, 03 Jan 2017 23:57:37 GMT EventedHTTPServer [::ffff:192.168.1.248] Muting event '2.10' notification for this connection since it originated here.
Tue, 03 Jan 2017 23:57:37 GMT ZWayServer Device Back Door, characteristic Lock Target State changed from 1 to false
Tue, 03 Jan 2017 23:57:37 GMT EventedHTTPServer [::ffff:192.168.1.248] HTTP Response is finished
Tue, 03 Jan 2017 23:57:43 GMT ZWayServer Got 1 updates.
Tue, 03 Jan 2017 23:57:43 GMT EventedHTTPServer [fe80::18ed:e196:d6a8:362c] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":0}]}
Tue, 03 Jan 2017 23:57:43 GMT EventedHTTPServer [::ffff:192.168.1.24] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":0}]}
Tue, 03 Jan 2017 23:57:43 GMT EventedHTTPServer [::ffff:192.168.1.243] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":0}]}
Tue, 03 Jan 2017 23:57:43 GMT EventedHTTPServer [::ffff:192.168.1.248] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":0}]}
Tue, 03 Jan 2017 23:57:43 GMT ZWayServer Device Back Door, characteristic Lock Current State changed from 1 to 0
Tue, 03 Jan 2017 23:57:43 GMT ZWayServer Updated characteristic Lock Current State on Back Door
Tue, 03 Jan 2017 23:57:43 GMT ZWayServer Returning LockTargetState of "0" because vdev.metrics.level returned "open"
Tue, 03 Jan 2017 23:57:43 GMT EventedHTTPServer [fe80::18ed:e196:d6a8:362c] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":0}]}
Tue, 03 Jan 2017 23:57:43 GMT EventedHTTPServer [::ffff:192.168.1.24] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":0}]}
Tue, 03 Jan 2017 23:57:43 GMT EventedHTTPServer [::ffff:192.168.1.243] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":0}]}
Tue, 03 Jan 2017 23:57:43 GMT EventedHTTPServer [::ffff:192.168.1.248] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":0}]}
Tue, 03 Jan 2017 23:57:43 GMT ZWayServer Device Back Door, characteristic Lock Target State changed from false to 0
Tue, 03 Jan 2017 23:57:43 GMT ZWayServer Updated characteristic Lock Target State on Back Door
Tue, 03 Jan 2017 23:57:45 GMT ZWayServer Got 1 updates.
Tue, 03 Jan 2017 23:57:45 GMT ZWayServer Returning LockTargetState of "0" because vdev.metrics.level returned "open"
```

**Comment by SphtKr** [comment]
Okay, merging this because good catch. I think this is probably a bug that needs fixing upstream though...hopefully this fix won't be necessary in the future. This probably isn't the only place where this happens, either.

**Pull request merged**
